// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_CRUD_OPERATION_API.Context;

#nullable disable

namespace Practice_CRUD_OPERATION_API.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20241207061714_new_data1")]
    partial class new_data1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practice_CRUD_OPERATION_API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Title = "Maths"
                        },
                        new
                        {
                            CourseId = 2,
                            Title = "Science"
                        },
                        new
                        {
                            CourseId = 3,
                            Title = "English"
                        });
                });

            modelBuilder.Entity("Practice_CRUD_OPERATION_API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentAge")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            StudentAge = 25,
                            StudentName = "John"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            StudentAge = 26,
                            StudentName = "Thomas"
                        });
                });

            modelBuilder.Entity("Practice_CRUD_OPERATION_API.Models.Student", b =>
                {
                    b.HasOne("Practice_CRUD_OPERATION_API.Models.Course", "Course")
                        .WithOne("Student")
                        .HasForeignKey("Practice_CRUD_OPERATION_API.Models.Student", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Practice_CRUD_OPERATION_API.Models.Course", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
